Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': ()
    '%w': ()

Style/SingleLineMethods:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Metrics/LineLength:
  Max: 100

Lint/MissingCopEnableDirective:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false
